# -*- coding: utf-8 -*-
"""AULA 8 TUPLAS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eCrJ3eub5z0h0OP1rCipEqaAGw9n6s-W
"""

#acessando tuplas
tupla = (1,3,6,5,56)
for n in tupla:
  print(n)

# CONVERTENDO UMA TUPLAS EM LISTA
tupla2 = (25,6,69)
n = list(tupla2)
print(n)

#IMPRIMIR UMA TUPLA
tupla3  = (2,3,6,9)

print(tupla3)



#CONVERTENDO UMA LISTA EM UMA TUPLA
lista1 = [1,23,4,5]

l = tuple(lista1)

print(l)

#DESEMPACOTAR ELEMENTOS DA LISTA
lista2 =  [1,3]

x, y = lista2

print("Coordenada 1", x)

print("Coordenada 2", y)

"""# EXERCÍCIOS"""

#1 -  Crie uma tupla chamada frutas com pelo menos 5 frutas diferentes. Em seguida, acesse e imprima o terceiro elemento da tupla.
tupla5 = ("Maçã", "Banana", "Morango", "Melão", "Limão")
print(tupla5[2])  #conta 0,1,2,3

#2
tupla4 = (1,2,3,4,5,6)
numeros = list(tupla4)
print(numeros)

#3
tupla6 = ("Janeiro", "Fevereiro", "Março", "Abriu", "Maio", "Junho", "Julho", "Agosto", "Setembro")
meses = tupla6
for n in tupla6:
 print(n)

#4
lista3 = [10,5,6,8]
l = tuple(lista3)
print(l)

#5
ponto =  [15,36]

x, y = ponto

print("Coordenada 1", x)

print("Coordenada 2", y)